name: Build Blocks

on: [ push, pull_request ]

jobs:
  build-linux:
    name: "Ubuntu Latest"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: "sudo apt-get update && sudo apt-get install libgsl-dev
              libxml2-dev libxslt1-dev libopenblas-dev libcomedi-dev
              gcc-arm-linux-gnueabihf"

      - name: "Export PYSUPSICTRL"
        run: "export PYSUPSICTRL=${{ github.workspace }}"

      - name: LinuxRT
        run: "make full_lib"

      - name: Linux MZ APO
        run: "make linux_mzapo"

      - name: Arduino Firmata
        run: "make arduino_firmata"

      - name: LinuxRT with SHV
        run: "make full_lib SHV=1"

      - name: Linux MZ APO with SHV
        run: "make linux_mzapo SHV=1"

